name: flutter_application_edutico
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  
  fonts:
  - family: Glacial Indifference
    fonts:
    - asset: assets/fonts/glacial.otf
  
  - family: Glacial Indifference Bold
    fonts:
    - asset: assets/fonts/GlacialIndifference-Bold.otf

  - family: Edutico
    fonts:
    - asset: assets/fonts/Edutico-Regular.otf
  
  assets:
    - 'assets/logoEdu.png'
    - 'assets/logoNome.png'
    - 'assets/prod1_1.jpg'
    - 'assets/catavento.png'
    - 'assets/prod1_2.jpg'
    - 'assets/prod1_3.jpg'
    - 'assets/prod2_1.jpg'
    - 'assets/prod2_2.jpg'
    - 'assets/prod2_3.jpg'
    - 'assets/prod3_1.jpg'
    - 'assets/prod3_2.jpg'
    - 'assets/prod3_3.jpg'
    - 'assets/prod4_1.jpg'
    - 'assets/prod4_2.jpg'
    - 'assets/prod4_3.jpg'
    - 'assets/prod5_1.jpg'
    - 'assets/prod5_2.jpg'
    - 'assets/prod5_3.jpg'
    - 'assets/prod6_1.jpg'
    - 'assets/prod6_2.jpg'
    - 'assets/prod6_3.jpg'
    - 'assets/prod7_1.jpg'
    - 'assets/prod7_2.jpg'
    - 'assets/prod7_3.jpg'
    - 'assets/prod8_1.jpg'
    - 'assets/prod8_2.jpg'
    - 'assets/prod8_3.jpg'
    - 'assets/prod9_1.jpg'
    - 'assets/prod9_2.jpg'
    - 'assets/prod9_3.jpg'
    - 'assets/prod10_1.jpg'
    - 'assets/prod10_2.jpg'
    - 'assets/prod10_3.jpg'
    - 'assets/prod11_1.jpg'
    - 'assets/prod11_2.jpg'
    - 'assets/prod11_3.jpg'
    - 'assets/prod12_1.jpg'
    - 'assets/prod12_2.jpg'
    - 'assets/prod12_3.jpg'
    - 'assets/prod13_1.jpg'
    - 'assets/prod13_2.jpg'
    - 'assets/prod13_3.jpg'
    - 'assets/prod14_1.jpg'
    - 'assets/prod14_2.jpg'
    - 'assets/prod14_3.jpg'
    - 'assets/prod15_1.jpg'
    - 'assets/prod15_2.jpg'
    - 'assets/prod15_3.jpg'
    - 'assets/prod16_1.jpg'
    - 'assets/prod16_2.jpg'
    - 'assets/prod16_3.jpg'
    - 'assets/prod17_1.jpg'
    - 'assets/prod17_2.jpg'
    - 'assets/prod17_3.jpg'
    - 'assets/prod18_1.jpg'
    - 'assets/prod18_2.jpg'
    - 'assets/prod18_3.jpg'
    - 'assets/prod19_1.jpg'
    - 'assets/prod19_2.jpg'
    - 'assets/prod19_3.jpg'
    - 'assets/prod20_1.jpg'
    - 'assets/prod20_2.jpg'
    - 'assets/prod20_3.jpg'
    - 'assets/prod21_1.jpg'
    - 'assets/prod21_2.jpg'
    - 'assets/prod21_3.jpg'
    - 'assets/prod22_1.jpg'
    - 'assets/prod22_2.jpg'
    - 'assets/prod22_3.jpg'
    - 'assets/prod23_1.jpg'
    - 'assets/prod23_2.jpg'
    - 'assets/prod23_3.jpg'
    - 'assets/prod24_1.jpg'
    - 'assets/prod24_2.jpg'
    - 'assets/prod24_3.jpg'
    - 'assets/prod25_1.jpg'
    - 'assets/prod25_2.jpg'
    - 'assets/prod25_3.jpg'
    - 'assets/prod26_1.jpg'
    - 'assets/prod26_2.jpg'
    - 'assets/prod26_3.jpg'
    - 'assets/prod27_1.jpg'
    - 'assets/prod27_2.jpg'
    - 'assets/prod27_3.jpg'
    - 'assets/prod28_1.jpg'
    - 'assets/prod28_2.jpg'
    - 'assets/prod28_3.jpg'
    - 'assets/prod29_1.jpg'
    - 'assets/prod29_2.jpg'
    - 'assets/prod29_3.jpg'
    - 'assets/prod30_1.jpg'
    - 'assets/prod30_2.jpg'
    - 'assets/prod30_3.jpg'