name: flutter_application_edutico
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  
  fonts:
  - family: Glacial Indifference
    fonts:
    - asset: assets/fonts/glacial.otf
  
  - family: Glacial Indifference Bold
    fonts:
    - asset: assets/fonts/GlacialIndifference-Bold.otf

  - family: Edutico
    fonts:
    - asset: assets/fonts/Edutico-Regular.otf
  
  assets:
    - 'assets/logoEdu.png'
    - 'assets/logoNome.png'
    - 'assets/prod1.jpeg'
    - 'assets/catavento.png'
    - 'assets/prod1_2.jpg'
    - 'assets/prod1_3.jpg'
    - 'assets/prod2_1.jpg'
    - 'assets/prod2_2.jpg'
    - 'assets/prod2_3.jpg'
    - 'assets/prod3_1.jpg'
    - 'assets/prod3_2.jpg'
    - 'assets/prod3_3.jpg'
    - 'assets/prod4_1.jpg'
    - 'assets/prod4_2.jpg'
    - 'assets/prod4_3.jpg'
    - 'assets/prod5_1.jpg'
    - 'assets/prod5_2.jpg'
    - 'assets/prod5_3.jpg'
    - 'assets/prod6_1.jpg'
    - 'assets/prod6_2.jpg'
    - 'assets/prod6_3.jpg'
    - 'assets/prod7_1.jpg'
    - 'assets/prod7_2.jpg'
    - 'assets/prod7_3.jpg'